title: Gezel Roadmap
author: Gezel.io
email: admin@gezel.io

assets: /assets
uploads: /uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://roadmap.gezel.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
